name: Create GameKit Unity Package
on:
  workflow_dispatch:
    inputs:
      gameKitVersion:
        description: 'v1.0.0_GameKit_internal'
        required: true
  push:
    branches:
      - dev

jobs:
  echo:
    
    runs-on: ubuntu-latest
    steps:
      - name: Switch to HTTPS git
        run: |
          rm -f ~/.gitconfig
          git config --local --unset url."git@github.com".insteadOf https://github.com || echo "OK"
          git config --local --unset url."git://".insteadOf https:// || echo "OK"

      - uses: actions/checkout@v2
      - name: Switch to SSH git
        run: |
          git config --local --replace-all url."git@github.com".insteadOf https://github.com
          git config --local --add url."git://".insteadOf https://

      - name: Checkout submodules
        env:
            GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
        run: |
          eval `ssh-agent -s`      
          echo "${{secrets.UNITY_FACEBOOK_SECRET}}" | ssh-add -
          git submodule update --init UnityFacebookSDK
          ssh-add -D     
          eval `ssh-agent -k`
    
    
    
    
    
    
    
        
        
        
        
        
        
        
        
        
        
        
        
        
          
          
 

      
      

