name: Create GameKit Unity Package
on:
  workflow_dispatch:
    inputs:
      gameKitVersion:
        description: 'v1.0.0_GameKit_internal'
        required: true
  push:
    branches:
      - dev

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Submodule
      - run: |
          mkdir -p $HOME/.ssh
          echo '${{ secrets.Rollic }}' > $HOME/.ssh/ssh.key
          chmod 600 $HOME/.ssh/ssh.key
          export GIT_SSH_COMMAND="ssh -i $HOME/.ssh/ssh.key"
          git submodule set-url submodules/UnityFacebookSDK git@github.com:ezgiustunel/UnityFacebookSDK.git
          git submodule update --init --recursive
          git submodule set-url submodules/UnityFacebookSDK git@github.com:ezgiustunel/UnityFacebookSDK.git
          unset GIT_SSH_COMMAND   

      
      

