name: Create GameKit Unity Package
on:
  workflow_dispatch:
    inputs:
      gameKitVersion:
        description: 'v1.0.0_GameKit_internal'
        required: true
  push:
    branches:
      - dev

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: |
          cd submodules
          git submodule set-url submodules/UnityFacebookSDK git@github.com:ezgiustunel/UnityFacebookSDK.git
          git submodule update --init --recursive
          git submodule set-url submodules/UnityFacebookSDK git@github.com:ezgiustunel/UnityFacebookSDK.git 

      
      

