name: Create GameKit Unity Package
on:
  workflow_dispatch:
    inputs:
      gameKitVersion:
        description: 'v1.0.0_GameKit_internal'
        required: true
  push:
    branches:
      - dev

jobs:
  echo:
    
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository to the GitHub Actions runner
      
      
      # Update references
      - name: Git Submodule Update
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive
        
        
        
        
        
        
        
        
        
        
        
        
        
          
          
 

      
      

