name: Create GameKit Unity Package
on:
  workflow_dispatch:
    inputs:
      gameKitVersion:
        description: 'v1.0.0_GameKit_internal'
        required: true
  push:
    branches:
      - dev

jobs:
  echo:
    
    runs-on: ubuntu-latest
    steps:
      - name: clone main repository
        uses: actions/checkout@v2

      - name: clone submodule
        uses: actions/checkout@v2
        with:
          repository: ezgiustunel/UnityFacebookSDK
          path: https://github.com/ezgiustunel/UnityFacebookSDK.git
          ref: v2
          ssh-key: ${{ secrets.Rollic }}
          persist-credentials: false
    
    
    
    
    
    
    
        
        
        
        
        
        
        
        
        
        
        
        
        
          
          
 

      
      

