name: Create GameKit Unity Package
on:
  workflow_dispatch:
    inputs:
      gameKitVersion:
        description: 'v1.0.0_GameKit_internal'
        required: true
  push:
    branches:
      - dev

jobs:
  echo:
    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master
        with:
          remote: true
        
        
        
        
        
        
        
          
          
 

      
      

